CREATE TABLE CTRL_HIST_TABELAS (
	TABLE_OWNER 	VARCHAR2(50) NOT NULL,
    TABLE_NAME      VARCHAR2(50) NOT NULL,
    PERIODO_HIST    NUMBER NOT NULL,
    PERIODO_TEMPO   VARCHAR2(2) NOT NULL,
    FLAG_ATIVO      NUMBER NOT NULL,
    PRIMARY KEY (TABLE_OWNER, TABLE_NAME)
);

